#!/usr/bin/env python3
"""Validate detecting-doc-bloat verdicts — envelope, chunk seams, assembly.

The contract is the engine's (`doclifecycle.bloat`), written up for authors in
../output-contract.md. This script enforces only what a *shape* check can see:
the verdict enum, the field set (including the fields a model may never
supply), per-verdict field requirements, the DISTILL status enum, and
scope-verdict exclusivity. It does not judge whether a verdict is *correct*,
and it cannot: every check that needs the corpus — that a path is a document,
that a unit occurs in it, that a destination is the index's owner, that a
DISTILL status equals the planning document's own file-bound marker, that a
scope enumerates to a non-empty member list — belongs to
`python3 -m doclifecycle bloat-audit`, which is the authority. Running this
first is how a worker catches a malformed verdict where it was produced,
instead of at the audit.

Three duties:

1. Final verdicts artifact (default):
       validate-bloat-output.py [FILE]          # FILE, or stdin if omitted
   Input must be the envelope `bloat-audit --verdicts` reads:
       {"schema_version": 1, "verdicts": [...], "completion": {...}}
   `schema_version` is optional and must be 1 when present; no other key is
   allowed, because the engine refuses one. A bare array — the legacy
   contract's report shape — fails with one legible error.

2. Chunk seam:
       validate-bloat-output.py --chunk FILE [--manifest FILE]
   Validates one chunk result {"chunk": "<id>", "verdicts": [...]} where it is
   produced. With --manifest — either planner's, plan-chunks.py's or
   `doclifecycle bloat-plan`'s — also cross-checks the slice: a
   single-document verdict may only name a document the chunk lists.
   A bulk `scope` verdict is deliberately not slice-bound — its subject is the
   whole corpus, and the engine enumerates its members from the index.

3. Assembly:
       validate-bloat-output.py --assemble DIR --manifest FILE --out FILE
                                [--allow-partial] [--unswept-out FILE]
   Reads DIR/<id>.json for every chunk in the manifest, seam-validates each,
   renumbers ids B1..Bn in manifest order (unique ids are the engine's rule,
   and approval binds a record's digest, never this label), and writes the
   envelope to --out. A missing or invalid chunk fails the assembly naming the
   chunk; --allow-partial instead records missing or invalid chunks loudly —
   each is named on stderr with its documents, inside the envelope's completion
   evidence, and (optionally) in --unswept-out for a caller to render.

Exit status: 0 valid; 1 contract violation; 2 bad input/usage.
On success prints a summary recomputed from the verdicts.
"""

import argparse
import json
import os
import sys
import unicodedata

ENGINE = os.path.abspath(os.path.join(
    os.path.dirname(__file__), "..", "..", "..", "engine",
))
sys.path.insert(0, ENGINE)

from doclifecycle import ARTIFACT_SCHEMA_VERSION  # noqa: E402
from doclifecycle import bloat as bloat_engine  # noqa: E402
from doclifecycle.report import DIGEST as UNIT_DIGEST, whole_number  # noqa: E402
from doclifecycle.results import Invalid  # noqa: E402

# A unit is a sha256 of its content, so anything
# else — a file:line, a paraphrase, a truncated digest — is refusable on sight.
# The engine refuses it too (`finding-invalid-unit`); catching it here is the
# whole point of a seam check where the verdict was produced.
#
# Matched with `fullmatch`, never `match`, and against the *unstripped* value:
# `$` matches before a trailing newline, so `"<64 hex>\n"` — the shape a copied
# digest arrives in when a transcription picks up its line ending — passed a
# `^...$` `.match()`. That value is the one that flows on to the engine, which
# looks it up verbatim and refuses it (`bloat-unknown-unit`), so trimming a
# copy before checking it would validate a string nobody downstream ever sees.
CUT = bloat_engine.CUT
CONDENSE = bloat_engine.CONDENSE
EXTRACT_AND_MOVE = bloat_engine.EXTRACT_AND_MOVE
MERGE_DOC = bloat_engine.MERGE_DOC
RETIRE_DOC = bloat_engine.RETIRE_DOC
DISTILL = bloat_engine.DISTILL

VERDICTS = bloat_engine.VERDICTS
VERDICT_FIELDS = bloat_engine.VERDICT_FIELDS
FORBIDDEN_VERDICT_FIELDS = bloat_engine.FORBIDDEN_VERDICT_FIELDS
SCOPE_SELECTORS = bloat_engine.SCOPE_SELECTORS
SCOPE_VERDICTS = bloat_engine.SCOPE_VERDICTS
DESTINATION_VERDICTS = bloat_engine.DESTINATION_VERDICTS
RESIDUE_VERDICTS = bloat_engine.RESIDUE_VERDICTS
PROPOSAL_VERDICTS = bloat_engine.PROPOSAL_VERDICTS
DISTILL_STATUSES = bloat_engine.DISTILL_STATUSES

# The legacy record's own fields. Naming them is worth a line each: a report
# regenerated by an old skill copy fails on its first field rather than on ten.
LEGACY_FIELDS = {
    "doc": "the engine's verdict names its document in 'path'",
    "location": "the engine's verdict names its content in 'units' (unit "
                "digests from `doclifecycle segment`), not a file:line",
    "payload": "distillation content is the doc-distiller's post-approval job",
}

SCHEMA_VERSION = ARTIFACT_SCHEMA_VERSION


SUMMARY_KEYS = ("cut", "condense", "extract_and_move",
                "merge_doc", "retire_doc", "distill")
SUMMARY_OF = {CUT: "cut", CONDENSE: "condense",
              EXTRACT_AND_MOVE: "extract_and_move", MERGE_DOC: "merge_doc",
              RETIRE_DOC: "retire_doc", DISTILL: "distill"}


def nonempty_str(v):
    return isinstance(v, str) and v.strip() != ""


def path_list(v):
    return isinstance(v, list) and v and all(nonempty_str(p) for p in v)


# --------------------------------------------------------------------------
# One verdict
# --------------------------------------------------------------------------

def check_fields(where, verdict, errs):
    for name in sorted(set(verdict) - set(VERDICT_FIELDS)):
        if name in FORBIDDEN_VERDICT_FIELDS:
            errs.append(f"{where}: {name!r} is not a field a verdict may carry "
                        f"— a bulk finding's members are enumerated from the "
                        f"index, never asserted by the model, so a list of "
                        f"files supplied here could authorize a mutation "
                        f"nobody enumerated")
        elif name in LEGACY_FIELDS:
            errs.append(f"{where}: {name!r} is a legacy record field — "
                        f"{LEGACY_FIELDS[name]}; regenerate with the current "
                        f"skill")
        else:
            errs.append(f"{where}: {name!r} is not a verdict field; expected "
                        f"{list(VERDICT_FIELDS)}")


def check_bulk(where, verdict, code, errs):
    """A judgment whose subject is a scope, not a document."""
    if code not in SCOPE_VERDICTS:
        errs.append(f"{where}: {code} cannot be a bulk judgment — only "
                    f"{list(SCOPE_VERDICTS)} applies uniformly to every member "
                    f"of a scope; anything else needs a per-document judgment "
                    f"nobody made")
        return
    for name in ("path", "units", "destination", "proposal", "status"):
        if verdict.get(name) is not None:
            errs.append(f"{where}: {name!r} does not apply to a bulk {code} — "
                        f"its subject is the scope, and its members come from "
                        f"the enumeration")

    scope = verdict["scope"]
    if not (isinstance(scope, dict) and len(scope) == 1
            and set(scope) <= set(SCOPE_SELECTORS)
            and nonempty_str(next(iter(scope.values())))):
        errs.append(f"{where}: a bulk scope must be exactly one of "
                    f"{list(SCOPE_SELECTORS)} naming a non-empty value, not "
                    f"{scope!r} — a scope nobody can expand into a file list "
                    f"cannot be reviewed or applied")

    # An *empty* sample is a real answer, and the engine records the finding
    # for it (`_reject_sample` requires only a list of non-blank strings): a
    # bulk judgment made from the enumeration alone read no member, and says
    # so. Requiring a member here would refuse a verdict bloat-audit accepts —
    # and because assembly forgives a *missing* chunk but never an invalid one,
    # a single false red like that discards a whole fan-out.
    sample = verdict.get("sample")
    if sample is not None and not (isinstance(sample, list)
                                   and all(nonempty_str(p) for p in sample)):
        errs.append(f"{where}: sample must be a list of paths — it records "
                    f"which members were read, and never stands in for the "
                    f"enumeration; an empty list is a legitimate answer, a "
                    f"blank or non-string entry names no member")


def check_destination_spelling(where, code, path, destination, errs):
    """The three destination faults a shape check can settle by itself.

    Everything else about a destination is the index's: whether it is a
    document, who owns the duplicated content, whether its kind accepts
    content, whether a residue path is free. These three need none of that,
    and each is refused by the engine today — the wording below is the
    engine's own, so a worker reads one explanation rather than two.

    Deliberately *not* checked here: the rest of
    `paths.repository_relative_problem` (an absolute path, a drive letter, a
    backslash, non-NFC form, a leading-dash component) and — for a move —
    whitespace. A move destination is only ever looked up in the index, and an
    indexed document may legitimately be spelled with a space in it
    (`bloat-audit` accepts `MERGE-DOC` into `docs/my guide.md` when that file
    is classified), so a blanket spelling port here would refuse verdicts the
    engine records. Whitespace is refused only on a residue destination, which
    the engine puts through `authorize_path` and which therefore cannot carry
    any.
    """
    if nonempty_str(path) and destination == path:
        if code in RESIDUE_VERDICTS:
            errs.append(f"{where}: {destination} is the planning artifact "
                        f"being distilled — its residue cannot be the "
                        f"document the same record retires")
        else:
            errs.append(f"{where}: {destination} is the document being judged "
                        f"— a move to itself changes nothing and would read as "
                        f"an approved edit")
        return

    if ".." in destination.split("/"):
        errs.append(f"{where}: {destination!r} traverses with '..' — a "
                    f"repository-relative path names a location inside the "
                    f"repository and never walks out of one, and no document "
                    f"the index holds is spelled that way")
        return

    if code in RESIDUE_VERDICTS:
        bad = next((c for c in destination
                    if c.isspace() or unicodedata.category(c) == "Zs"), None)
        if bad is not None:
            errs.append(f"{where}: {destination!r} contains whitespace "
                        f"(U+{ord(bad):04X}) — whitespace makes a path "
                        f"ambiguous to quote and impossible to distinguish by "
                        f"eye, and a residue document is one this "
                        f"distillation authors, so name it without any")


def check_one_document(where, verdict, code, errs):
    if not nonempty_str(verdict.get("path")):
        errs.append(f"{where}: needs a path — the document this verdict judges")
    units = verdict.get("units")
    if not path_list(units):
        errs.append(f"{where}: must name at least one assertion unit — the "
                    f"unit digests `doclifecycle segment --repo . --path "
                    f"<path>` prints for that document")
    else:
        for unit in units:
            if not UNIT_DIGEST.fullmatch(unit):
                errs.append(f"{where}: {unit!r} is not an assertion unit — a "
                            f"unit is the 64-character sha256 digest `segment` "
                            f"prints, copied verbatim; a line number, a quote, "
                            f"or a truncated digest names no content the "
                            f"engine can bind an edit to")

    if verdict.get("sample") is not None:
        errs.append(f"{where}: is a judgment about one document, so a sample "
                    f"says nothing — sampling prioritizes review of a bulk "
                    f"scope and never stands in for reading the subject")

    destination = verdict.get("destination")
    if code in DESTINATION_VERDICTS + RESIDUE_VERDICTS:
        # Optional: the index derives a move's destination for content it finds
        # elsewhere, and a retire-only distillation names none.
        if destination is not None and not nonempty_str(destination):
            errs.append(f"{where}: {code}'s destination must be a document "
                        f"path, or absent")
        elif destination is not None:
            check_destination_spelling(where, code, verdict.get("path"),
                                       destination, errs)
    elif destination is not None:
        errs.append(f"{where}: {code} moves nothing, so it names no "
                    f"destination — only "
                    f"{list(DESTINATION_VERDICTS + RESIDUE_VERDICTS)} do")

    proposal = verdict.get("proposal")
    if code in PROPOSAL_VERDICTS:
        if not nonempty_str(proposal):
            errs.append(f"{where}: {code} replaces text, so it must carry the "
                        f"replacement")
    elif proposal is not None:
        errs.append(f"{where}: {code} writes no replacement text, so it "
                    f"carries no proposal")

    status = verdict.get("status")
    if code == DISTILL:
        if status not in DISTILL_STATUSES:
            errs.append(f"{where}: a {DISTILL} verdict's status must be one of "
                        f"{list(DISTILL_STATUSES)}, not {status!r} — copied "
                        f"from the planning document's own '> Status:' marker, "
                        f"which bloat-audit checks it against")
    elif status is not None:
        errs.append(f"{where}: only {DISTILL} carries a lifecycle status")


def validate_verdict(i, verdict):
    where = f"verdicts[{i}]"
    if not isinstance(verdict, dict):
        return [f"{where}: must be an object"]
    if nonempty_str(verdict.get("id")):
        where += f" ({verdict['id']})"

    errs = []
    check_fields(where, verdict, errs)
    if not nonempty_str(verdict.get("id")):
        errs.append(f"{where}: needs a non-empty id")

    code = verdict.get("verdict")
    if code not in VERDICTS:
        errs.append(f"{where}: {code!r} is not a bloat verdict — expected one "
                    f"of {list(VERDICTS)}")
        return errs

    if not nonempty_str(verdict.get("evidence")):
        errs.append(f"{where}: states no evidence — a bloat verdict is a value "
                    f"judgment, and one that does not say why is not "
                    f"reviewable")

    if verdict.get("scope") is not None:
        check_bulk(where, verdict, code, errs)
    else:
        check_one_document(where, verdict, code, errs)
    return errs


def check_unique_ids(verdicts):
    errs, seen = [], {}
    for i, v in enumerate(verdicts):
        if isinstance(v, dict) and nonempty_str(v.get("id")):
            vid = v["id"]
            if vid in seen:
                errs.append(f"verdicts[{i}]: id {vid!r} is used by more than "
                            f"one verdict (first at verdicts[{seen[vid]}]) — "
                            f"two records a reviewer cannot tell apart cannot "
                            f"be approved apart")
            else:
                seen[vid] = i
    return errs


def validate_verdicts(verdicts):
    errs = []
    for i, v in enumerate(verdicts):
        errs.extend(validate_verdict(i, v))
    errs.extend(check_unique_ids(verdicts))
    return errs


# --------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------

def count_verdicts(verdicts):
    counts = dict.fromkeys(SUMMARY_KEYS, 0)
    for v in verdicts:
        code = v.get("verdict") if isinstance(v, dict) else None
        if code in SUMMARY_OF:
            counts[SUMMARY_OF[code]] += 1
    return counts


def fail(errs):
    for e in errs:
        print(e, file=sys.stderr)
    print(f"\nFAILED: {len(errs)} contract violation(s)", file=sys.stderr)
    return 1


def ok(verdicts):
    print(f"OK: {len(verdicts)} verdict(s) valid")
    print(f"summary: {json.dumps(count_verdicts(verdicts))}")
    return 0


def read_json(src):
    raw = sys.stdin.read() if src is None else open(src, encoding="utf-8").read()
    return json.loads(raw)


# --------------------------------------------------------------------------
# Duty 1: the envelope
# --------------------------------------------------------------------------

ENVELOPE = ('the verdicts artifact is the envelope bloat-audit reads — '
            '{"schema_version": 1, "verdicts": [...], "completion": {...}}')


def envelope_errors(data):
    if isinstance(data, list):
        return [f"{ENVELOPE}, not a bare array — regenerate with the current "
                f"skill"]
    if not isinstance(data, dict):
        return [f"{ENVELOPE}; got {type(data).__name__}"]
    errs = []
    for name in sorted(set(data) - {"schema_version", "verdicts", "completion"}):
        errs.append(f"{name!r} is not an envelope key — {ENVELOPE}, and the "
                    f"engine refuses any other key")
    version = data.get("schema_version", SCHEMA_VERSION)
    # `_whole_number` first, matching the engine's `report.whole_number`: a bare
    # `!=` accepts `True` and `1.0`, both equal to `1` in Python, so an envelope
    # declaring either passed a check whose own message says integer version.
    if not whole_number(version) or version != SCHEMA_VERSION:
        errs.append(f"schema_version {version!r} is not supported; this "
                    f"contract is integer version {SCHEMA_VERSION}")
    if not isinstance(data.get("verdicts"), list):
        errs.append(f"{ENVELOPE}; 'verdicts' must be an array")
    if not isinstance(data.get("completion"), dict):
        errs.append(f"{ENVELOPE}; 'completion' must be an object")
    return errs


def run_final(src):
    try:
        data = read_json(src)
    except (OSError, json.JSONDecodeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    errs = envelope_errors(data)
    if errs:
        return fail(errs)
    verdicts = data["verdicts"]
    errs = validate_verdicts(verdicts)
    return fail(errs) if errs else ok(verdicts)


# --------------------------------------------------------------------------
# Duty 2: the chunk seam
# --------------------------------------------------------------------------

def read_manifest(path):
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    chunks = data.get("chunks") if isinstance(data, dict) else None
    if not isinstance(chunks, list) or not all(
            isinstance(c, dict) and nonempty_str(c.get("id")) for c in chunks):
        raise ValueError(f"manifest {path}: expected {{'chunks': [{{'id': ...}}, ...]}}")
    return data


def chunk_doc_paths(chunk):
    """The documents a chunk covers, from either planner's manifest.

    plan-chunks.py writes `docs: [{"path", "lines", "hint"}]`; the engine's
    `bloat-plan` writes `documents: [path]`. Both are legitimate work orders
    for the same seam, and reading only one of them would silently empty the
    slice — refusing every verdict in a chunk as "outside" it.
    """
    docs = chunk.get("docs")
    if isinstance(docs, list):
        # The `path` must be a string, not merely present: the `documents`
        # branch below already filters that way, and a chunk carrying
        # `docs: [{}]` yielded `[None]`, which `', '.join(...)` at the
        # --allow-partial notice raised an uncaught TypeError on — a traceback
        # out of the assembler instead of a diagnosis, on the one path whose
        # whole job is surviving an incomplete fan-out.
        return [d["path"] for d in docs
                if isinstance(d, dict) and isinstance(d.get("path"), str)]
    documents = chunk.get("documents")
    if isinstance(documents, list):
        return [p for p in documents if isinstance(p, str)]
    return []


def chunk_shape_errors(data):
    if not (isinstance(data, dict) and set(data) == {"chunk", "verdicts"}
            and nonempty_str(data.get("chunk"))
            and isinstance(data.get("verdicts"), list)):
        return ['chunk result must be exactly {"chunk": "<id>", '
                '"verdicts": [...]}']
    return []


def slice_errors(data, chunk):
    """A single-document verdict names a document the chunk was given."""
    allowed = set(chunk_doc_paths(chunk))
    errs = []
    for i, v in enumerate(data["verdicts"]):
        if not isinstance(v, dict) or v.get("scope") is not None:
            continue
        path = v.get("path")
        if nonempty_str(path) and path not in allowed:
            errs.append(f"verdicts[{i}]: {path} is outside this chunk's slice "
                        f"— a worker judges the documents it was given, and "
                        f"the index answers everything else")
    return errs


def validate_chunk_result(data, chunk):
    errs = chunk_shape_errors(data)
    if errs:
        return errs
    errs = validate_verdicts(data["verdicts"])
    if chunk is not None:
        if data["chunk"] != chunk["id"]:
            errs.append(f"result names chunk {data['chunk']!r} but was matched "
                        f"to {chunk['id']!r}")
        errs.extend(slice_errors(data, chunk))
    return errs


def run_chunk(path, manifest_path):
    try:
        data = read_json(path)
    except (OSError, json.JSONDecodeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    chunk = None
    if manifest_path:
        try:
            chunks = read_manifest(manifest_path)["chunks"]
        except (OSError, ValueError, json.JSONDecodeError) as e:
            print(f"error: {e}", file=sys.stderr)
            return 2
        if isinstance(data, dict) and nonempty_str(data.get("chunk")):
            chunk = next((c for c in chunks if c["id"] == data["chunk"]), None)
            if chunk is None:
                return fail([f"chunk {data['chunk']!r} is not in the manifest"])
    errs = validate_chunk_result(data, chunk)
    return fail(errs) if errs else ok(data["verdicts"])


# --------------------------------------------------------------------------
# Duty 3: assembly
# --------------------------------------------------------------------------

def run_assemble(dir_, manifest_path, out, allow_partial, unswept_out):
    try:
        manifest = read_manifest(manifest_path)
        chunks = manifest["chunks"]
    except (OSError, ValueError, json.JSONDecodeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    raw_plan = (manifest if manifest.get("status") == "ok"
                else manifest.get("engine_plan"))
    plan = bloat_engine.chunk_plan_from_dict(raw_plan)
    if isinstance(plan, Invalid):
        print("error: manifest carries no valid engine_plan — completion "
              "evidence must preserve the authentic public bloat-plan artifact",
              file=sys.stderr)
        for problem in plan.problems:
            print(f"error: {problem.code}: {problem.message}", file=sys.stderr)
        return 2
    planned = [(chunk.chunk_id, list(chunk.documents)) for chunk in plan.chunks]
    dispatched = [(chunk["id"], chunk_doc_paths(chunk)) for chunk in chunks]
    if dispatched != planned:
        print("error: scheduler chunks do not exactly match engine_plan ids and "
              "document membership", file=sys.stderr)
        return 2
    errs, unswept, outcomes = [], [], []
    for chunk in chunks:
        path = os.path.join(dir_, chunk["id"] + ".json")
        documents = chunk_doc_paths(chunk)
        if not os.path.exists(path):
            if allow_partial:
                print(f"note: --allow-partial: chunk {chunk['id']} has no "
                      f"result file — UNSWEPT, and these documents were not "
                      f"audited this run: {', '.join(documents)}", file=sys.stderr)
                unswept.append({"chunk": chunk["id"], "docs": documents})
                outcomes.append(bloat_engine.ChunkOutcome.missing(
                    chunk["id"], "result file was not produced",
                ))
                continue
            errs.append(f"chunk {chunk['id']}: no result file at {path} — "
                        f"partial assembly refused")
            continue
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            if allow_partial:
                detail = f"unreadable result: {e}"
                print(f"note: --allow-partial: chunk {chunk['id']} has an "
                      f"invalid result — UNSWEPT: {detail}", file=sys.stderr)
                unswept.append({"chunk": chunk["id"], "docs": documents})
                outcomes.append(bloat_engine.ChunkOutcome.invalid(
                    chunk["id"], detail,
                ))
                continue
            errs.append(f"chunk {chunk['id']}: unreadable result: {e}")
            continue
        chunk_errs = validate_chunk_result(data, chunk)
        if chunk_errs:
            if allow_partial:
                detail = "; ".join(chunk_errs)
                print(f"note: --allow-partial: chunk {chunk['id']} has an "
                      f"invalid result — UNSWEPT: {detail}", file=sys.stderr)
                unswept.append({"chunk": chunk["id"], "docs": documents})
                outcomes.append(bloat_engine.ChunkOutcome.invalid(
                    chunk["id"], detail,
                ))
                continue
            errs.extend(f"chunk {chunk['id']}: {e}" for e in chunk_errs)
            continue
        outcomes.append(bloat_engine.ChunkOutcome.complete(
            chunk["id"], data["verdicts"],
        ))
    if errs:
        return fail(errs)

    audit_input = bloat_engine.assemble_bloat_input(plan, outcomes)
    if isinstance(audit_input, Invalid):
        return fail([f"{problem.code}: {problem.message}"
                     for problem in audit_input.problems])
    payload = audit_input.to_dict()
    with open(out, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)
        f.write("\n")
    if unswept_out:
        with open(unswept_out, "w", encoding="utf-8") as f:
            json.dump(unswept, f, indent=2)
            f.write("\n")
    if unswept:
        print(f"note: {len(unswept)} chunk(s) unswept — the next plan's "
              f"content-addressed resume sweeps exactly them", file=sys.stderr)
    return ok(payload["verdicts"])


def main():
    ap = argparse.ArgumentParser(
        description="Validate detecting-doc-bloat verdicts "
                    "(envelope / seam / assembly).")
    ap.add_argument("file", nargs="?",
                    help="final verdicts envelope (default: stdin)")
    ap.add_argument("--chunk", help="validate one chunk result file at the seam")
    ap.add_argument("--manifest",
                    help="plan-chunks.py manifest for slice cross-checks")
    ap.add_argument("--assemble", metavar="DIR",
                    help="assemble every manifest chunk's DIR/<id>.json into --out")
    ap.add_argument("--out", help="where --assemble writes the verdicts envelope")
    ap.add_argument("--allow-partial", action="store_true",
                    help="--assemble only: skip missing chunks loudly, naming "
                         "each and its documents on stderr")
    ap.add_argument("--unswept-out", metavar="FILE",
                    help="--assemble only: write the skipped chunks as a JSON "
                         "[{chunk, docs}] gap list (empty when none)")
    args = ap.parse_args()

    if args.chunk and args.assemble:
        print("usage: --chunk and --assemble are mutually exclusive", file=sys.stderr)
        return 2
    if args.assemble:
        if not (args.manifest and args.out):
            print("usage: --assemble requires --manifest and --out", file=sys.stderr)
            return 2
        return run_assemble(args.assemble, args.manifest, args.out,
                            args.allow_partial, args.unswept_out)
    if args.chunk:
        if args.file:
            print("usage: --chunk takes no positional artifact", file=sys.stderr)
            return 2
        if args.allow_partial or args.unswept_out:
            print("usage: --allow-partial/--unswept-out apply only to "
                  "--assemble", file=sys.stderr)
            return 2
        return run_chunk(args.chunk, args.manifest)
    if args.allow_partial or args.manifest or args.out or args.unswept_out:
        print("usage: --manifest/--out/--allow-partial/--unswept-out apply "
              "only to --chunk/--assemble", file=sys.stderr)
        return 2
    return run_final(args.file)


if __name__ == "__main__":
    sys.exit(main())
