#!/usr/bin/env python3
"""Validate detecting-doc-bloat verdicts — envelope, chunk seams, assembly.

The contract is the engine's (`doclifecycle.bloat`), written up for authors in
../output-contract.md. This script enforces only what a *shape* check can see:
the verdict enum, the field set (including the fields a model may never
supply), per-verdict field requirements, the DISTILL status enum, and
scope-verdict exclusivity. It does not judge whether a verdict is *correct*,
and it cannot: every check that needs the corpus — that a path is a document,
that a unit occurs in it, that a destination is the index's owner, that a
DISTILL status equals the planning document's own file-bound marker, that a
scope enumerates to a non-empty member list — belongs to
`python3 -m doclifecycle bloat-audit`, which is the authority. Running this
first is how a worker catches a malformed verdict where it was produced,
instead of at the audit.

Three duties:

1. Final verdicts artifact (default):
       validate-bloat-output.py [FILE]          # FILE, or stdin if omitted
   Input must be the envelope `bloat-audit --verdicts` reads:
       {"schema_version": 1, "verdicts": [...]}
   `schema_version` is optional and must be 1 when present; no other key is
   allowed, because the engine refuses one. A bare array — the legacy
   contract's report shape — fails with one legible error.

2. Chunk seam:
       validate-bloat-output.py --chunk FILE [--manifest FILE]
   Validates one chunk result {"chunk": "<id>", "verdicts": [...]} where it is
   produced. With --manifest — either planner's, plan-chunks.py's or
   `doclifecycle bloat-plan`'s — also cross-checks the slice: a
   single-document verdict may only name a document the chunk lists.
   A bulk `scope` verdict is deliberately not slice-bound — its subject is the
   whole corpus, and the engine enumerates its members from the index.

3. Assembly:
       validate-bloat-output.py --assemble DIR --manifest FILE --out FILE
                                [--allow-partial] [--unswept-out FILE]
   Reads DIR/<id>.json for every chunk in the manifest, seam-validates each,
   renumbers ids B1..Bn in manifest order (unique ids are the engine's rule,
   and approval binds a record's digest, never this label), and writes the
   envelope to --out. A missing or invalid chunk fails the assembly naming the
   chunk; --allow-partial instead skips MISSING chunks loudly — each is named
   on stderr with its documents, and --unswept-out writes the same gap list as
   JSON ({chunk, docs} entries) for a caller to render. The gap stays out of
   the envelope itself: bloat-audit refuses an envelope carrying any key but
   `schema_version` and `verdicts`. An invalid chunk always fails.

Exit status: 0 valid; 1 contract violation; 2 bad input/usage.
On success prints a summary recomputed from the verdicts.
"""

import argparse
import json
import os
import re
import sys

# `report.DIGEST`, mirrored: a unit is a sha256 of its content, so anything
# else — a file:line, a paraphrase, a truncated digest — is refusable on sight.
# The engine refuses it too (`finding-invalid-unit`); catching it here is the
# whole point of a seam check where the verdict was produced.
UNIT_DIGEST = re.compile(r"^[0-9a-f]{64}$")

CUT = "CUT"
CONDENSE = "CONDENSE"
EXTRACT_AND_MOVE = "EXTRACT-AND-MOVE"
MERGE_DOC = "MERGE-DOC"
RETIRE_DOC = "RETIRE-DOC"
DISTILL = "DISTILL"

VERDICTS = (CUT, CONDENSE, EXTRACT_AND_MOVE, MERGE_DOC, RETIRE_DOC, DISTILL)

# Mirrors of the engine's own tuples (bloat.py); the framing of each refusal is
# the engine's too, so a worker reads one explanation, not two.
VERDICT_FIELDS = ("id", "verdict", "path", "units", "evidence",
                  "destination", "proposal", "status", "scope", "sample")
FORBIDDEN_VERDICT_FIELDS = ("files", "members", "occurrences", "contention")
SCOPE_SELECTORS = ("set", "glob", "kind")
SCOPE_VERDICTS = (RETIRE_DOC,)
DESTINATION_VERDICTS = (EXTRACT_AND_MOVE, MERGE_DOC)
RESIDUE_VERDICTS = (DISTILL,)
PROPOSAL_VERDICTS = (CONDENSE, EXTRACT_AND_MOVE)
DISTILL_STATUSES = ("pending-implementation", "ready")

# The legacy record's own fields. Naming them is worth a line each: a report
# regenerated by an old skill copy fails on its first field rather than on ten.
LEGACY_FIELDS = {
    "doc": "the engine's verdict names its document in 'path'",
    "location": "the engine's verdict names its content in 'units' (unit "
                "digests from `doclifecycle segment`), not a file:line",
    "payload": "distillation content is the doc-distiller's post-approval job",
}

SCHEMA_VERSION = 1
SUMMARY_KEYS = ("cut", "condense", "extract_and_move",
                "merge_doc", "retire_doc", "distill")
SUMMARY_OF = {CUT: "cut", CONDENSE: "condense",
              EXTRACT_AND_MOVE: "extract_and_move", MERGE_DOC: "merge_doc",
              RETIRE_DOC: "retire_doc", DISTILL: "distill"}


def nonempty_str(v):
    return isinstance(v, str) and v.strip() != ""


def path_list(v):
    return isinstance(v, list) and v and all(nonempty_str(p) for p in v)


# --------------------------------------------------------------------------
# One verdict
# --------------------------------------------------------------------------

def check_fields(where, verdict, errs):
    for name in sorted(set(verdict) - set(VERDICT_FIELDS)):
        if name in FORBIDDEN_VERDICT_FIELDS:
            errs.append(f"{where}: {name!r} is not a field a verdict may carry "
                        f"— a bulk finding's members are enumerated from the "
                        f"index, never asserted by the model, so a list of "
                        f"files supplied here could authorize a mutation "
                        f"nobody enumerated")
        elif name in LEGACY_FIELDS:
            errs.append(f"{where}: {name!r} is a legacy record field — "
                        f"{LEGACY_FIELDS[name]}; regenerate with the current "
                        f"skill")
        else:
            errs.append(f"{where}: {name!r} is not a verdict field; expected "
                        f"{list(VERDICT_FIELDS)}")


def check_bulk(where, verdict, code, errs):
    """A judgment whose subject is a scope, not a document."""
    if code not in SCOPE_VERDICTS:
        errs.append(f"{where}: {code} cannot be a bulk judgment — only "
                    f"{list(SCOPE_VERDICTS)} applies uniformly to every member "
                    f"of a scope; anything else needs a per-document judgment "
                    f"nobody made")
        return
    for name in ("path", "units", "destination", "proposal", "status"):
        if verdict.get(name) is not None:
            errs.append(f"{where}: {name!r} does not apply to a bulk {code} — "
                        f"its subject is the scope, and its members come from "
                        f"the enumeration")

    scope = verdict["scope"]
    if not (isinstance(scope, dict) and len(scope) == 1
            and set(scope) <= set(SCOPE_SELECTORS)
            and nonempty_str(next(iter(scope.values())))):
        errs.append(f"{where}: a bulk scope must be exactly one of "
                    f"{list(SCOPE_SELECTORS)} naming a non-empty value, not "
                    f"{scope!r} — a scope nobody can expand into a file list "
                    f"cannot be reviewed or applied")

    sample = verdict.get("sample")
    if sample is not None and not path_list(sample):
        errs.append(f"{where}: sample must be a list of paths — it records "
                    f"which members were read, and never stands in for the "
                    f"enumeration")


def check_one_document(where, verdict, code, errs):
    if not nonempty_str(verdict.get("path")):
        errs.append(f"{where}: needs a path — the document this verdict judges")
    units = verdict.get("units")
    if not path_list(units):
        errs.append(f"{where}: must name at least one assertion unit — the "
                    f"unit digests `doclifecycle segment --repo . --path "
                    f"<path>` prints for that document")
    else:
        for unit in units:
            if not UNIT_DIGEST.match(unit.strip()):
                errs.append(f"{where}: {unit!r} is not an assertion unit — a "
                            f"unit is the 64-character sha256 digest `segment` "
                            f"prints, copied verbatim; a line number, a quote, "
                            f"or a truncated digest names no content the "
                            f"engine can bind an edit to")

    if verdict.get("sample") is not None:
        errs.append(f"{where}: is a judgment about one document, so a sample "
                    f"says nothing — sampling prioritizes review of a bulk "
                    f"scope and never stands in for reading the subject")

    destination = verdict.get("destination")
    if code in DESTINATION_VERDICTS + RESIDUE_VERDICTS:
        # Optional: the index derives a move's destination for content it finds
        # elsewhere, and a retire-only distillation names none.
        if destination is not None and not nonempty_str(destination):
            errs.append(f"{where}: {code}'s destination must be a document "
                        f"path, or absent")
    elif destination is not None:
        errs.append(f"{where}: {code} moves nothing, so it names no "
                    f"destination — only "
                    f"{list(DESTINATION_VERDICTS + RESIDUE_VERDICTS)} do")

    proposal = verdict.get("proposal")
    if code in PROPOSAL_VERDICTS:
        if not nonempty_str(proposal):
            errs.append(f"{where}: {code} replaces text, so it must carry the "
                        f"replacement")
    elif proposal is not None:
        errs.append(f"{where}: {code} writes no replacement text, so it "
                    f"carries no proposal")

    status = verdict.get("status")
    if code == DISTILL:
        if status not in DISTILL_STATUSES:
            errs.append(f"{where}: a {DISTILL} verdict's status must be one of "
                        f"{list(DISTILL_STATUSES)}, not {status!r} — copied "
                        f"from the planning document's own '> Status:' marker, "
                        f"which bloat-audit checks it against")
    elif status is not None:
        errs.append(f"{where}: only {DISTILL} carries a lifecycle status")


def validate_verdict(i, verdict):
    where = f"verdicts[{i}]"
    if not isinstance(verdict, dict):
        return [f"{where}: must be an object"]
    if nonempty_str(verdict.get("id")):
        where += f" ({verdict['id']})"

    errs = []
    check_fields(where, verdict, errs)
    if not nonempty_str(verdict.get("id")):
        errs.append(f"{where}: needs a non-empty id")

    code = verdict.get("verdict")
    if code not in VERDICTS:
        errs.append(f"{where}: {code!r} is not a bloat verdict — expected one "
                    f"of {list(VERDICTS)}")
        return errs

    if not nonempty_str(verdict.get("evidence")):
        errs.append(f"{where}: states no evidence — a bloat verdict is a value "
                    f"judgment, and one that does not say why is not "
                    f"reviewable")

    if verdict.get("scope") is not None:
        check_bulk(where, verdict, code, errs)
    else:
        check_one_document(where, verdict, code, errs)
    return errs


def check_unique_ids(verdicts):
    errs, seen = [], {}
    for i, v in enumerate(verdicts):
        if isinstance(v, dict) and nonempty_str(v.get("id")):
            vid = v["id"]
            if vid in seen:
                errs.append(f"verdicts[{i}]: id {vid!r} is used by more than "
                            f"one verdict (first at verdicts[{seen[vid]}]) — "
                            f"two records a reviewer cannot tell apart cannot "
                            f"be approved apart")
            else:
                seen[vid] = i
    return errs


def validate_verdicts(verdicts):
    errs = []
    for i, v in enumerate(verdicts):
        errs.extend(validate_verdict(i, v))
    errs.extend(check_unique_ids(verdicts))
    return errs


# --------------------------------------------------------------------------
# Reporting
# --------------------------------------------------------------------------

def count_verdicts(verdicts):
    counts = dict.fromkeys(SUMMARY_KEYS, 0)
    for v in verdicts:
        code = v.get("verdict") if isinstance(v, dict) else None
        if code in SUMMARY_OF:
            counts[SUMMARY_OF[code]] += 1
    return counts


def fail(errs):
    for e in errs:
        print(e, file=sys.stderr)
    print(f"\nFAILED: {len(errs)} contract violation(s)", file=sys.stderr)
    return 1


def ok(verdicts):
    print(f"OK: {len(verdicts)} verdict(s) valid")
    print(f"summary: {json.dumps(count_verdicts(verdicts))}")
    return 0


def read_json(src):
    raw = sys.stdin.read() if src is None else open(src, encoding="utf-8").read()
    return json.loads(raw)


# --------------------------------------------------------------------------
# Duty 1: the envelope
# --------------------------------------------------------------------------

ENVELOPE = ('the verdicts artifact is the envelope bloat-audit reads — '
            '{"schema_version": 1, "verdicts": [...]}')


def envelope_errors(data):
    if isinstance(data, list):
        return [f"{ENVELOPE}, not a bare array — regenerate with the current "
                f"skill"]
    if not isinstance(data, dict):
        return [f"{ENVELOPE}; got {type(data).__name__}"]
    errs = []
    for name in sorted(set(data) - {"schema_version", "verdicts"}):
        errs.append(f"{name!r} is not an envelope key — {ENVELOPE}, and the "
                    f"engine refuses any other key")
    version = data.get("schema_version", SCHEMA_VERSION)
    if version != SCHEMA_VERSION:
        errs.append(f"schema_version {version!r} is not supported; this "
                    f"contract is integer version {SCHEMA_VERSION}")
    if not isinstance(data.get("verdicts"), list):
        errs.append(f"{ENVELOPE}; 'verdicts' must be an array")
    return errs


def run_final(src):
    try:
        data = read_json(src)
    except (OSError, json.JSONDecodeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    errs = envelope_errors(data)
    if errs:
        return fail(errs)
    verdicts = data["verdicts"]
    errs = validate_verdicts(verdicts)
    return fail(errs) if errs else ok(verdicts)


# --------------------------------------------------------------------------
# Duty 2: the chunk seam
# --------------------------------------------------------------------------

def load_manifest(path):
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    chunks = data.get("chunks") if isinstance(data, dict) else None
    if not isinstance(chunks, list) or not all(
            isinstance(c, dict) and nonempty_str(c.get("id")) for c in chunks):
        raise ValueError(f"manifest {path}: expected {{'chunks': [{{'id': ...}}, ...]}}")
    return chunks


def chunk_doc_paths(chunk):
    """The documents a chunk covers, from either planner's manifest.

    plan-chunks.py writes `docs: [{"path", "lines", "hint"}]`; the engine's
    `bloat-plan` writes `documents: [path]`. Both are legitimate work orders
    for the same seam, and reading only one of them would silently empty the
    slice — refusing every verdict in a chunk as "outside" it.
    """
    docs = chunk.get("docs")
    if isinstance(docs, list):
        return [d.get("path") for d in docs if isinstance(d, dict)]
    documents = chunk.get("documents")
    if isinstance(documents, list):
        return [p for p in documents if isinstance(p, str)]
    return []


def chunk_shape_errors(data):
    if not (isinstance(data, dict) and set(data) == {"chunk", "verdicts"}
            and nonempty_str(data.get("chunk"))
            and isinstance(data.get("verdicts"), list)):
        return ['chunk result must be exactly {"chunk": "<id>", '
                '"verdicts": [...]}']
    return []


def slice_errors(data, chunk):
    """A single-document verdict names a document the chunk was given."""
    allowed = set(chunk_doc_paths(chunk))
    errs = []
    for i, v in enumerate(data["verdicts"]):
        if not isinstance(v, dict) or v.get("scope") is not None:
            continue
        path = v.get("path")
        if nonempty_str(path) and path not in allowed:
            errs.append(f"verdicts[{i}]: {path} is outside this chunk's slice "
                        f"— a worker judges the documents it was given, and "
                        f"the index answers everything else")
    return errs


def validate_chunk_result(data, chunk):
    errs = chunk_shape_errors(data)
    if errs:
        return errs
    errs = validate_verdicts(data["verdicts"])
    if chunk is not None:
        if data["chunk"] != chunk["id"]:
            errs.append(f"result names chunk {data['chunk']!r} but was matched "
                        f"to {chunk['id']!r}")
        errs.extend(slice_errors(data, chunk))
    return errs


def run_chunk(path, manifest_path):
    try:
        data = read_json(path)
    except (OSError, json.JSONDecodeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    chunk = None
    if manifest_path:
        try:
            chunks = load_manifest(manifest_path)
        except (OSError, ValueError, json.JSONDecodeError) as e:
            print(f"error: {e}", file=sys.stderr)
            return 2
        if isinstance(data, dict) and nonempty_str(data.get("chunk")):
            chunk = next((c for c in chunks if c["id"] == data["chunk"]), None)
            if chunk is None:
                return fail([f"chunk {data['chunk']!r} is not in the manifest"])
    errs = validate_chunk_result(data, chunk)
    return fail(errs) if errs else ok(data["verdicts"])


# --------------------------------------------------------------------------
# Duty 3: assembly
# --------------------------------------------------------------------------

def run_assemble(dir_, manifest_path, out, allow_partial, unswept_out):
    try:
        chunks = load_manifest(manifest_path)
    except (OSError, ValueError, json.JSONDecodeError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    errs, verdicts, unswept = [], [], []
    for chunk in chunks:
        path = os.path.join(dir_, chunk["id"] + ".json")
        if not os.path.exists(path):
            if allow_partial:
                docs = chunk_doc_paths(chunk)
                print(f"note: --allow-partial: chunk {chunk['id']} has no "
                      f"result file — UNSWEPT, and these documents were not "
                      f"audited this run: {', '.join(docs)}", file=sys.stderr)
                unswept.append({"chunk": chunk["id"], "docs": docs})
                continue
            errs.append(f"chunk {chunk['id']}: no result file at {path} — "
                        f"partial assembly refused")
            continue
        try:
            with open(path, encoding="utf-8") as f:
                data = json.load(f)
        except (OSError, json.JSONDecodeError) as e:
            errs.append(f"chunk {chunk['id']}: unreadable result: {e}")
            continue
        chunk_errs = validate_chunk_result(data, chunk)
        if chunk_errs:
            errs.extend(f"chunk {chunk['id']}: {e}" for e in chunk_errs)
            continue
        verdicts.extend(data["verdicts"])
    if errs:
        return fail(errs)

    for n, v in enumerate(verdicts, 1):
        v["id"] = f"B{n}"
    with open(out, "w", encoding="utf-8") as f:
        json.dump({"schema_version": SCHEMA_VERSION, "verdicts": verdicts},
                  f, indent=2)
        f.write("\n")
    if unswept_out:
        with open(unswept_out, "w", encoding="utf-8") as f:
            json.dump(unswept, f, indent=2)
            f.write("\n")
    if unswept:
        print(f"note: {len(unswept)} chunk(s) unswept — the next plan's "
              f"content-addressed resume sweeps exactly them", file=sys.stderr)
    return ok(verdicts)


def main():
    ap = argparse.ArgumentParser(
        description="Validate detecting-doc-bloat verdicts "
                    "(envelope / seam / assembly).")
    ap.add_argument("file", nargs="?",
                    help="final verdicts envelope (default: stdin)")
    ap.add_argument("--chunk", help="validate one chunk result file at the seam")
    ap.add_argument("--manifest",
                    help="plan-chunks.py manifest for slice cross-checks")
    ap.add_argument("--assemble", metavar="DIR",
                    help="assemble every manifest chunk's DIR/<id>.json into --out")
    ap.add_argument("--out", help="where --assemble writes the verdicts envelope")
    ap.add_argument("--allow-partial", action="store_true",
                    help="--assemble only: skip missing chunks loudly, naming "
                         "each and its documents on stderr")
    ap.add_argument("--unswept-out", metavar="FILE",
                    help="--assemble only: write the skipped chunks as a JSON "
                         "[{chunk, docs}] gap list (empty when none)")
    args = ap.parse_args()

    if args.chunk and args.assemble:
        print("usage: --chunk and --assemble are mutually exclusive", file=sys.stderr)
        return 2
    if args.assemble:
        if not (args.manifest and args.out):
            print("usage: --assemble requires --manifest and --out", file=sys.stderr)
            return 2
        return run_assemble(args.assemble, args.manifest, args.out,
                            args.allow_partial, args.unswept_out)
    if args.chunk:
        if args.file:
            print("usage: --chunk takes no positional artifact", file=sys.stderr)
            return 2
        if args.allow_partial or args.unswept_out:
            print("usage: --allow-partial/--unswept-out apply only to "
                  "--assemble", file=sys.stderr)
            return 2
        return run_chunk(args.chunk, args.manifest)
    if args.allow_partial or args.manifest or args.out or args.unswept_out:
        print("usage: --manifest/--out/--allow-partial/--unswept-out apply "
              "only to --chunk/--assemble", file=sys.stderr)
        return 2
    return run_final(args.file)


if __name__ == "__main__":
    sys.exit(main())
